title: The Typewriter
description: A website with a blog
header_text: ""
footer_text: Copyright 2020 Rithika Raghu
header_feature_image: ../uploads/banner-3.jpg
bannerheight: 50vmax
logo: ../uploads/android-chrome-512x512-1-.png
favicon: ../uploads/android-chrome-512x512-1-.png
gridlayout: true
fixednavbar: true
upzoom: true
items: []
