title: The Typewriter
description: A website with a blog
header_text: Typography through the eyes of history
footer_text: Copyright 2020 Rithika Raghu
header_feature_image: ../uploads/jason-yu-dbeeqk0ifrq-unsplash.jpg
bannerheight: 20vmax
logo: ../uploads/the-typewriter-logo-1.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
